### ISSUE TITLE
Example of config and state properties

### ISSUE THREAD

**Issue by psvensson** [royaltm/node-zmq-raft#17]
Hi and thanks for a very nice node.js raft implementation.  I wonder if you could add o he documentation example on how the arguments for the state and config listeners look like. 

Right now I'm setting up some local raft nodes (as described in the README) looking at what comes out and trying to apply that to my code, but it would be very nice with a clear definition of how the data looks.

**Comment by royaltm** [comment]
If you are implementing your own state machine extending StateMachineBase class, then each element of the `entries` array is a buffer which can be read using LogEntry API:

```js
const raft = require("zmq-raft");

class MyStateMachine extends raft.api.StateMachineBase {
//...
    applyEntries(logEntries, nextIndex, currentTerm, snapshot) {
        for (let [index, item] of logEntries.entries()) {
            let entry = raft.common.LogEntry.bufferToLogEntry(item, nextIndex + index);
            console.log("state entry: log-index=%s term=%s", entry.logIndex, entry.readEntryTerm());
            //  user data of the log entry 
            console.log(entry.readEntryData());
            if (entry.isStateEntry) {
              console.log("this is state entry");
            } else if (entry.isConfigEntry) {
              console.log("this is config entry");
            } else {
              console.log("this is checkpoint entry");
            }
      }
      super.applyEntries(logEntries, nextIndex, currentTerm, snapshot) ;
    }
}
```

The same applies to the "pulse" event listener of the `raft.client.ZmqRaftPeerSub` client:

```
sub.on('pulse', (lastIndex, currentTerm, entries) => {
        let nextIndex = lastIndex - entries.length + 1;
        for (let [index, item] of logEntries.entries()) {
            let entry = raft.common.LogEntry.bufferToLogEntry(item, nextIndex + index);
            //...
        }
});
```

**Comment by royaltm** [comment]
Please see https://github.com/royaltm/node-zmq-raft/blob/master/lib/common/log_entry.js for the log entry API and 
https://github.com/royaltm/node-zmq-raft/blob/master/PROTO.md for the description of the log entry content :

```
The RAFT log's entry data is constructed as follows:

12-bytes reqid,
1-byte log entry type: 0 - STATE, 1 - CONFIG, 2 - CHECKPOINT (see: [RAFT](https://github.com/royaltm/node-zmq-raft/blob/master/RAFT.md)),
7-byte log entry term (least significant byte first),
arbitrary log data.
```

**Comment by psvensson** [comment]
Thanks a lot! I think this would be great to add to the main README also

**Comment by royaltm** [comment]
The arbitrary data of the state log entries is... arbitrary, whatever data you feed the raft cluster with `requestUpdate` - will be there.

The checkpoint entry data is always a single byte = `0xC0` which is a [MessagePacked](https://msgpack.org/index.html) representation of `nil`.

The config entries data is a MessagePacked peer list and depending on whether it is a transitional config or the final config the structure is either an object:

transitional entry:
```
{ old: old_peer_list, new: new_peer_list }
```

or just a final `peer_list` array.

The peer list as an `Array<Peer>` where each `Peer` is a tuple of strings: `[peer_id, peer_url]`.

**Comment by psvensson** [comment]
Yes, I see. I think my problem was more that , coming in without more than cursory knowledge (and admittedly not having read and understood Raft completely) I was searching for some small example in how to use in in practice. Even though this looks like it is very easy, especially with your implementation of it, I think it would help newcomers a lot. The rest of the README is very helpful and I think a small but practical custom statemachine example (e.g. actually sending or receiving changes to an array or something simple like that) would help a lot and be the final piece of the puzzle

**Comment by royaltm** [comment]
Update readme: https://github.com/royaltm/node-zmq-raft/blob/master/README.md#interpreting-log-entries

**Comment by psvensson** [comment]
Wonderful, thank you. Closing this issue then.

**Comment by royaltm** [comment]
I'm glad I could help.
