### ISSUE TITLE
How do I update state so that new members of the cluster receive it?

### ISSUE THREAD

**Issue by psvensson** [royaltm/node-zmq-raft#19]
First of all, it might be something else wrong I am doing, but I have so far been able to create a two raft nodes which seem to connect, where each node have its own peer address and broadcast address (or more specifically port since each run on localhost).

I now try to create a client to update state on teh first raft node, this succeeds and I'm able to append logs, but nothing happens on the other node.

I note that when creating a client of some kind (regardless of whether it is raft.client.ZmqRaftClient or raft.client.ZmqRaftSubscriber, I need to pass a static string defining the current peers.

The client is created when the first serer has just started and then it's only itself in the peer list. Could this be why no updates are received at the other node? If so, how do one solve this scenario? I would like to have raft members change over time.

**Comment by royaltm** [comment]
What you are doing at least from your description is sound. I suspect you have a configuration issue.

Both RAFT servers (not clients) should be created using the same peer list, so they know how do they find each other.
The only difference between both server configuration should be their own peer ID and the data path.

If you are running both peers on the same machine, be careful as so they DO NOT store their RAFT state in the same directory! Otherwise the behavior is undefined.

The path should be uniquely setup for each RAFT peer:

```
  data: {
    path: "/path/to/raft/data"
  },
```

Alternatively you can use the ` appendIdToPath: true`  switch that makes RAFT builder create a sub-directory with the peer ID as its name.
https://github.com/royaltm/node-zmq-raft/blob/master/config/example.hjson#L7


Clients raft.client.ZmqRaftClient or raft.client.ZmqRaftSubscriber do not need a full peer list, they will fetch it once they connect to any peer in the cluster.

I think your issue is that the RAFT peer servers do not see each other.

Set the environment variable:
```
export DEBUG=*
```
before you start node, so you will have a full insight of what is happening on each RAFT peer and/or clients.

**Comment by royaltm** [comment]
I re-read your comment and have some further thoughts. 
Apparently you are starting both RAFT peers as standalone server, so they only know each other.

It is possible to dynamically add or remove peers from the cluster, but it requires a special procedure.
I described it in both RAFT.md and README.md, but I;m suggesting that you should start with a simple setup first.

Start with providing an initial peer list to both RAFT servers, where they know about each other. Test your program and see if that works. Once you play with it for a bit and learn your ways around the whole system, then try to do more advanced tasks, like changing peer ownership or log compaction.

in any case zmq-raft supports all such scenarios

**Comment by psvensson** [comment]
Sorry for the delay. I now set up (I think) the correct connection information for both peers so that they should be able to find each other from start, and that does not work either, so I have made some basic mistake somwhere, most possibly. 

Here is the debug output from the first node;

 zmq-raft:socket socket.connect: tcp://127.0.0.1:6000 +0ms
  zmq-raft:socket socket.connect: tcp://127.0.0.1:7000 +0ms
building raft server with id: 1
  zmq-raft:builder building raft server +0ms
  zmq-raft:builder ensuring directory data.path: "raft/1" +1ms
id 1 so starting to send
  zmq-raft:builder initializing persistence +1ms
  zmq-raft:builder initializing log +0ms
  zmq-raft:filelog opening log: "raft/1/log" +0ms
  zmq-raft:builder initializing state machine +0ms
  zmq-raft:broadcast-sm url: tcp://127.0.0.1:7500 +1ms
  zmq-raft:broadcast-sm heartbeat interval: 500 ms +0ms
  zmq-raft:file-persistence file "raft/1/raft.pers" opened for reading: 32 +0ms
  zmq-raft:file-persistence file "raft/1/state.pers" opened for reading: 33 +0ms
  zmq-raft:file-persistence finished reading: 0 bytes +1ms
  zmq-raft:snapshotfile reading "raft/1/snap" +1ms
  zmq-raft:file-persistence finished reading: 75 bytes +0ms
  zmq-raft:file-persistence file "raft/1/state.pers" opened with flags: a +0ms
  zmq-raft:file-persistence ready: {"lastApplied":0} +0ms
  zmq-raft:file-persistence file "raft/1/raft.pers" opened with flags: a +0ms
  zmq-raft:file-persistence ready: {"currentTerm":3,"votedFor":"1","peers":[{"id":"1","url":"tcp://127.0.0.1:6000","pub":"tcp://127.0.0.1:6500"},{"id":"2","url":"tcp://127.0.0.1:7000","pub":"tcp://127.0.0.1:7500"}],"peersUpdateRequest":null,"peersIndex":null} +0ms
  zmq-raft:broadcast-sm ready at: tcp://127.0.0.1:7500 +1ms
  zmq-raft:snapshotfile read "raft/1/snap" logIndex: 0, logTerm: 0, dataSize: 0 +0ms
  zmq-raft:snapshotfile ready "raft/1/snap" +0ms
  zmq-raft:indexfile opening existing: "raft/1/log/00000/00/00/00000000000001.rlog" +0ms
  zmq-raft:indexfile opened: 00000000000001 +0ms
  zmq-raft:filelog reading request ids from index files down to: 1 +1ms
  zmq-raft:filelog read: 0 requests in 0.0 seconds +0ms
  zmq-raft:filelog first index: 1, last index: 0, last term: 0 +0ms
  zmq-raft:builder initializing raft peer: "1" +0ms
  zmq-raft:builder prevent spiral elections: true +0ms
  zmq-raft:builder raft-state: Symbol(Follower) term: 3 +1ms
  zmq-raft:service ready at: tcp://127.0.0.1:7000 +0ms
  zmq-raft:service term: 3 votedFor: "1" +0ms
  zmq-raft:service peers: 1 peersUpdateRequest: null peersIndex: null +0ms
  zmq-raft:service commit: 0 applied: 0 +0ms
  zmq-raft:leader election timeout term: 4 +600ms
  zmq-raft:builder raft-state: Symbol(Candidate) term: 4 +0ms
  zmq-raft:rpc-socket rpc.connect: tcp://127.0.0.1:7000 +62ms
  zmq-raft:service request vote rpc: no such peer: 1 +2ms

-------

And here is the same from the other one;

 zmq-raft:socket socket.connect: tcp://127.0.0.1:6000 +0ms
  zmq-raft:socket socket.connect: tcp://127.0.0.1:7000 +0ms
building raft server with id: 2
  zmq-raft:builder building raft server +0ms
  zmq-raft:builder ensuring directory data.path: "raft/2" +0ms
  zmq-raft:builder initializing persistence +1ms
  zmq-raft:builder initializing log +1ms
  zmq-raft:filelog opening log: "raft/2/log" +0ms
  zmq-raft:builder initializing state machine +0ms
  zmq-raft:broadcast-sm url: tcp://127.0.0.1:6500 +0ms
  zmq-raft:broadcast-sm heartbeat interval: 500 ms +0ms
  zmq-raft:file-persistence file "raft/2/raft.pers" opened for reading: 32 +1ms
  zmq-raft:file-persistence file "raft/2/state.pers" opened for reading: 33 +0ms
  zmq-raft:file-persistence finished reading: 0 bytes +1ms
  zmq-raft:snapshotfile reading "raft/2/snap" +0ms
  zmq-raft:file-persistence finished reading: 50 bytes +0ms
  zmq-raft:file-persistence file "raft/2/state.pers" opened with flags: a +0ms
  zmq-raft:file-persistence ready: {"lastApplied":0} +1ms
  zmq-raft:file-persistence file "raft/2/raft.pers" opened with flags: a +0ms
  zmq-raft:file-persistence ready: {"currentTerm":2,"votedFor":"2","peers":[{"id":"1","url":"tcp://127.0.0.1:6000","pub":"tcp://127.0.0.1:6500 "},{"id":"2","url":"tcp://127.0.0.1:7000","pub":"tcp://127.0.0.1:7500"}],"peersUpdateRequest":null,"peersIndex":null} +0ms
  zmq-raft:broadcast-sm ready at: tcp://127.0.0.1:6500 +0ms
  zmq-raft:snapshotfile read "raft/2/snap" logIndex: 0, logTerm: 0, dataSize: 0 +1ms
  zmq-raft:snapshotfile ready "raft/2/snap" +0ms
  zmq-raft:indexfile opening existing: "raft/2/log/00000/00/00/00000000000001.rlog" +0ms
  zmq-raft:indexfile opened: 00000000000001 +0ms
  zmq-raft:filelog reading request ids from index files down to: 1 +0ms
  zmq-raft:filelog read: 0 requests in 0.0 seconds +0ms
  zmq-raft:filelog first index: 1, last index: 0, last term: 0 +0ms
  zmq-raft:builder initializing raft peer: "2" +1ms
  zmq-raft:builder prevent spiral elections: true +0ms
  zmq-raft:builder raft-state: Symbol(Follower) term: 2 +1ms
  zmq-raft:service ready at: tcp://127.0.0.1:6000 +0ms
  zmq-raft:service term: 2 votedFor: "2" +0ms
  zmq-raft:service peers: 1 peersUpdateRequest: null peersIndex: null +0ms
  zmq-raft:service commit: 0 applied: 0 +0ms
  zmq-raft:leader election timeout term: 3 +555ms
  zmq-raft:builder raft-state: Symbol(Candidate) term: 3 +0ms
  zmq-raft:rpc-socket rpc.connect: tcp://127.0.0.1:6000 +52ms
  zmq-raft:service request vote rpc: no such peer: 2 +0ms
------------------------------------

It is quite a bit of info, but I was hoping that you might spot if there is anything obvious amiss.

**Comment by royaltm** [comment]
I don't like why you have: "
"zmq-raft:service ready at: tcp://127.0.0.1:6000 +0ms" for raft id 2 and 
"zmq-raft:service ready at: tcp://127.0.0.1:7000" for raft id 1

and at the same time define:
```
[{"id":"1","url":"tcp://127.0.0.1:6000","pub":"tcp://127.0.0.1:6500 "},
 {"id":"2","url":"tcp://127.0.0.1:7000","pub":"tcp://127.0.0.1:7500"}]
```
as your peer list.

I don't have enough time on me right now to get into detail, but it looks like your peers are bound to a wrong socket (a cross-over), if you still struggling send me the config that you generate for each peer, or create a gist with code.

**Comment by psvensson** [comment]
My apologies for returning to this so late. In a nutshell - You are right. I did on another window try to connect to the wrong IP address, using the external IP of the machine rather than localhost that I was testing with.

So closing this now.
