### ISSUE TITLE
Using node-zmq-raft on a "slow" network

### ISSUE THREAD

**Issue by josephwinston** [royaltm/node-zmq-raft#4]
I would like to use node-zqm-raft on a network that has throughput rates that range between 20 and 250 kbits/sec.  These values are much lower than the maximum 11 Mbps what you would see even on a 802.11b WiFi (https://en.wikipedia.org/wiki/IEEE_802.11b-1999).

Can this be done by increasing the values found in https://github.com/royaltm/node-zmq-raft/blob/master/lib/common/constants.js by multiplying like 550 (11e6/200000)?

Specifically this type of increment:
```
ELECTION_TIMEOUT_MAX: 300 * 550
RPC_TIMEOUT: 50 * 550
APPEND_ENTRIES_HEARTBEAT_INTERVAL: 70 * 550
APPEND_ENTRIES_RPC_TIMEOUT_MAX: 140 * 550
SERVER_RESPONSE_TIMEOUT: 500 * 550
SERVER_ELECTION_GRACE_DELAY: 300 * 550

BROADCAST_HEARTBEAT_INTERVAL: 500  * 2 ;; once a second is fine
```

Or is there a better approach if I want to use this code on a "slow" network?

**Comment by royaltm** [comment]
While RAFT was designed with properties to react to peer unresponsiveness pretty fast, I don't see while it wouldn't be working with slower throughput. Unless the connections between peers won't be frequently broken or the total connection uptime will be no less than its downtime it should be working fine.

A factor like 550 is IMHO too large. While ELECTION TIMEOUT is served by default after 300 ms, multiplying it by 550 would make it 2:45 minutes, which in turn would make the protocol pretty clumsy. I would start with *10, see if it works, perhaps go up to 20 or down by half... etc.

My other advice would be to not alter the constants, but rather use options to override them. Every component can be initialized with options overriding these values. This way you don't even need to make any changes in this repository.

E.g. see https://github.com/royaltm/node-zmq-raft/blob/master/config/default.hjson#L110

Servers:
https://github.com/royaltm/node-zmq-raft/blob/master/lib/server/raft.js#L142
https://github.com/royaltm/node-zmq-raft/blob/master/lib/server/broadcast_state_machine.js#L72

Clients:
https://github.com/royaltm/node-zmq-raft/blob/master/lib/client/zmq_raft_client.js#L112
https://github.com/royaltm/node-zmq-raft/blob/master/lib/client/zmq_raft_subscriber.js#L110

Hope this helps.

**Comment by josephwinston** [comment]
Excellent. That makes perfect sense. 

The transport layer is tcp/ip. It is just on a slow media.
